const footballTeams = [
    "Manchester United",
    "Liverpool",
    "Real Madrid",
    "FC Barcelona",
    "Bayern Munich",
    "Juventus",
    "Paris Saint-Germain",
    "Chelsea",
    "Manchester City",
    "Arsenal",
    "Tottenham Hotspur",
    "AC Milan",
    "Inter Milan",
    "Atletico Madrid",
    "Borussia Dortmund",
    "Ajax",
    "FC Porto",
    "Benfica",
    "AS Roma",
    "Napoli",
    "Boca Juniors",
    "River Plate",
    "Santos FC",
    "Flamengo",
    "Palmeiras",
    "Corinthians",
    "Sao Paulo FC",
    "FC Porto",
    "Sporting Lisbon",
    "Sevilla FC",
    "Valencia CF",
    "Villarreal CF",
    "Atlético Mineiro",
    "Cruzeiro",
    "Fluminense",
    "Botafogo",
    "Grêmio",
    "Internacional",
    "Vasco da Gama",
    "São Paulo FC",
    "LA Galaxy",
    "New York City FC",
    "Toronto FC",
    "Chicago Fire",
    "Los Angeles FC",
    "Seattle Sounders FC",
    "Orlando City SC",
    "Atlanta United FC",
    "Portland Timbers",
  ];
  
export default footballTeams
  